import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthProvider } from './lib/utils/context/AuthContext'
import './globals.css'
import { TasksProvider } from './lib/utils/context/TasksContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Chronos',
    default: 'Chronos'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <TasksProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </TasksProvider>
    </AuthProvider>
  )
}
